window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t674_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var backgroundImage=rec.querySelector('.t674__img-holder');if(!backgroundImage)return;backgroundImage.onload=function(){var delay=0;var allRecords=document.getElementById('allrecords');if(allRecords.getAttribute('data-blocks-animationoff')!=='yes'){delay=600}
setTimeout(function(){document.body.classList.add('t674__body_with-bg')},delay)};var event=document.createEvent('HTMLEvents');event.initEvent('load',!0,!1);backgroundImage.dispatchEvent(event)}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});menu.addEventListener('menuOverflow',function(){t450_checkSize(recid)});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed')}else{menu.classList.remove('t450__overflowed')}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){if(link.getAttribute('data-highlighted-by-user')!=='y')link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t794_init(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(!hook)return;var hookLinks=document.querySelectorAll('a[href="'+hook+'"]');hookLinks=Array.prototype.filter.call(hookLinks,function(hookLink){var isSubmenuAllowed=hookLink.getAttribute('data-submenu-disallowed')!=='yes';if(isSubmenuAllowed){hookLink.classList.add('t794__tm-link');hookLink.setAttribute('data-tooltip-menu-id',recid);return!0}
return!1});var parentMenu=hookLinks.length?hookLinks[0].closest('[data-menu]'):null;var tooltipMenu=rec.querySelector('.t794__tooltip-menu');var isParentFixed=parentMenu&&window.getComputedStyle(parentMenu).position==='fixed';if(tooltipMenu)tooltipMenu.setAttribute('data-pos-fixed',isParentFixed?'yes':'no');t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t_onFuncLoad('t_submenublocks__highlightActiveLinks',function(){t_submenublocks__highlightActiveLinks('.t794__list_item a')});if(menu.hasAttribute('data-full-submenu-mob')&&(window.isMobile||'ontouchend' in document)){t_onFuncLoad('t_submenublocks__setFullScreenMenu',function(){t_submenublocks__setFullScreenMenu(menu)})}}
function t794_addArrow(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenuBlock=rec?rec.querySelector('.t794'):null;var isArrowAppend=submenuBlock.getAttribute('data-add-arrow');if(!isArrowAppend)return;hookLinks=Array.prototype.slice.call(hookLinks);hookLinks.forEach(function(hookLink){var arrow=document.createElement('div');arrow.classList.add('t794__arrow');hookLink.appendChild(arrow);var isInsideZero=hookLink.closest('.tn-atom');var hasCustomBorderColor=window.getComputedStyle(hookLink).borderColor!=='rgba(0, 0, 0, 0)';if(isInsideZero&&!hasCustomBorderColor){hookLink.style.borderColor='initial';hookLink.style.border='none'}})}
function t794_setUpMenu(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenu=rec?rec.querySelector('.t794__tooltip-menu'):null;if(!submenu)return;var menuBlock=rec?rec.querySelector('.t794'):null;var verticalIndent=menuBlock.getAttribute('data-tooltip-margin');var content=submenu.querySelector('.t794__content');var hooksAndSubmenu=hookLinks.concat(submenu);if(window.innerWidth>980&&!('ontouchend' in document)){t_onFuncLoad('t_submenublocks__addEventsDesktop',function(){t_submenublocks__addEventsDesktop(submenu,hooksAndSubmenu,verticalIndent,'.t794')})}else{t_onFuncLoad('t_submenublocks__addEventsMobile',function(){t_submenublocks__addEventsMobile(submenu,hookLinks,verticalIndent,'.t794')})}
window.addEventListener('scroll',t_throttle(function(){if(content){content.addEventListener('mouseleave',function(){if(submenu.classList.contains('t794__tooltip-menu_show')){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')})}})}},300));var tooltipLinks=document.querySelectorAll('.t794__tooltip-menu a[href*="#"]');Array.prototype.forEach.call(tooltipLinks,function(tooltipLink){tooltipLink.addEventListener('click',function(){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')});var menuList=document.querySelectorAll('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466');Array.prototype.forEach.call(menuList,function(menu){var event=document.createEvent('Event');event.initEvent('clickedAnchorInTooltipMenu',!0,!0);menu.dispatchEvent(event)});Array.prototype.forEach.call(tooltipLinks,function(link){link.classList.remove('t-active')});tooltipLink.classList.add('t-active')})})}
function t972_init(recid){var cookies=t972_getCookie('t_cookiesConsentGiven');if(cookies.val){t972_acceptCookies();return}else{var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;wrapper.classList.remove('t972_closed');t972_addEvents(recid);t972_addCookieEvents(recid);t972_translateToggle(recid)}}
function t972_initPreview(recid){t972_addEvents(recid);t972_translateToggle(recid)}
function t972_getCookie(name){var matches=document.cookie.match(new RegExp('(?:^|; )'+name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+'=([^;]*)'));var cookie={name:'',val:''};if(matches){try{cookie={name:name,val:decodeURIComponent(matches[1])}}catch(e){}}
return cookie}
function t972_createCookie(name,value,days){var expires;if(days){var date=new Date();var dayInMs=24*60*60*1000;date.setTime(date.getTime()+days*dayInMs);expires='; expires='+date.toGMTString()}else{expires=''}
document.cookie=name+'='+value+expires+'; path=/'}
function t972_confirmCookies(list){var checkBoxes=document.querySelectorAll('.t972__categories input[name="cookie_type"]');var selectedCookies=[];if(list==='all'){Array.prototype.forEach.call(checkBoxes,function(checkBox){checkBox.checked=!0})}
Array.prototype.forEach.call(checkBoxes,function(checkBox){if(checkBox.checked===!0){selectedCookies.push(checkBox.value)}});var allowedCookiesList=JSON.stringify(selectedCookies);t972_createCookie('t_cookiesCategories',allowedCookiesList,365);t972_acceptCookies()}
function t972_acceptCookies(){var allowedCookiesList=t972_getCookie('t_cookiesCategories').val;var scriptsList=document.querySelectorAll('script[data-tilda-cookie-type]');Array.prototype.forEach.call(scriptsList,function(item){if(allowedCookiesList.indexOf(item.getAttribute('data-tilda-cookie-type'))!==-1){if(item.getAttribute('type')&&item.getAttribute('type')==='text/plain'){var str=item.innerHTML;item.innerHTML='';item.setAttribute('type','text/javascript');item.innerHTML=str.replace('}, 2000);','}, 200);');if(allowedCookiesList.indexOf('advertising')==-1){if(str.indexOf('google-analytics')!==-1){item.innerHTML=str.replace('auto','{ storeGac: false }')}}
if(allowedCookiesList.indexOf('analytics')!==-1){if(typeof tildastat=='function'){tildastat('cookieenabled')}else{setTimeout(function(){if(typeof tildastat=='function'){tildastat('cookieenabled')}},1000)}}
item.setAttribute('data-tilda-cookie-consent','accepted')}
if(item.getAttribute('data-src')){item.setAttribute('src',item.getAttribute('data-src'));item.setAttribute('data-tilda-cookie-consent','accepted')}}});t972_createCookie('t_cookiesConsentGiven','true',365)}
function t972_addEvents(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;var settingsBtn=wrapper.querySelector('.t972__settings-btn');var settingsHeader=wrapper.querySelector('.t972__settings-header');var categoryTitle=wrapper.querySelectorAll('.t972__category-header');var categoryToggle=wrapper.querySelectorAll('.t972__toggle-input');var cookiesBanner=wrapper.querySelector('.t972__banner');var settingsBanner=wrapper.querySelector('.t972__settings');settingsBtn.addEventListener('click',function(){cookiesBanner.style.display='none';settingsBanner.style.display='flex'});settingsHeader.addEventListener('click',function(){cookiesBanner.style.display='block';settingsBanner.style.display='none'});Array.prototype.forEach.call(categoryTitle,function(title){title.addEventListener('click',function(){var categoryBody=title.closest('.t972__category').querySelector('.t972__category-body');title.classList.toggle('t972__opened');title.style.pointerEvents='none';t972_slideToggle(categoryBody,title,300)})});Array.prototype.forEach.call(categoryToggle,function(toggle){toggle.addEventListener('change',function(){var toggleText=toggle.closest('.t972__category-toggle').querySelector('.t972__toggle-txt');if(toggle.checked){toggleText.classList.add('t972__category-enabled');toggleText.textContent=t972_trans('enabled')}else{toggleText.classList.remove('t972__category-enabled');toggleText.textContent=t972_trans('disabled')}})})}
function t972_slideToggle(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=500;if(window.getComputedStyle(target).display==='none'){return t972_slideDown(target,triggerElement,duration)}else{return t972_slideUp(target,triggerElement,duration)}}
function t972_slideUp(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=500;target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.boxSizing='border-box';target.style.height=target.offsetHeight+'px';target.offsetHeight;target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.display='none';target.style.height='';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}
function t972_slideDown(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=500;target.style.display='';var cashedDisplay=window.getComputedStyle(target).display;if(cashedDisplay==='none')cashedDisplay='block';target.style.display=cashedDisplay;var targetHeight=target.offsetHeight;target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';target.offsetHeight;target.style.boxSizing='border-box';target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.height=targetHeight+'px';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.height='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}
function t972_addCookieEvents(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;var confirmBtn=wrapper.querySelector('.t972__confirm-btn');var acceptBtn=wrapper.querySelector('.t972__accept-btn');var cookiesBanner=wrapper.querySelector('.t972__banner');var settingsBanner=wrapper.querySelector('.t972__settings');confirmBtn.addEventListener('click',function(){t972_confirmCookies('selected');cookiesBanner.style.display='none';settingsBanner.style.display='none'});acceptBtn.addEventListener('click',function(){t972_confirmCookies('all');cookiesBanner.style.display='none';settingsBanner.style.display='none'})}
function t972_translateToggle(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;var category=wrapper.querySelectorAll('.t972__category-toggle');Array.prototype.forEach.call(category,function(cat){var categoryText=cat.querySelectorAll('.t972__toggle-txt');Array.prototype.forEach.call(categoryText,function(item){if(item.classList.contains('js_always-enabled')){item.textContent=t972_trans('alwaysEnabled')}else{var itemParent=item.parentNode;var categoryInput=itemParent.querySelector('.t972__toggle-input');if(categoryInput.checked){item.textContent=t972_trans('enabled')}else{item.textContent=t972_trans('disabled')}}})})}
function t972_trans(key){var data={alwaysEnabled:{EN:'Always Enabled',RU:'Всегда разрешено',FR:'Toujours actif',DE:'Immer aktiv',ES:'Activas siempre',PT:'Sempre ativos',JA:'常にアクティブ',ZH:'始終啟用',UK:'Завжди дозволено',PL:'Zawsze aktywne',KK:'Әрқашан қосылады',IT:'Sempre attivi',LV:'Vienmēr iespējots',},enabled:{EN:'Enabled',RU:'Разрешено',FR:'Actif',DE:'Aktiv',ES:'Activas',PT:'Ativos',JA:'アクティブ',ZH:'启用',UK:'Дозволено',PL:'Aktywne',KK:'Қосылды',IT:'Attivi',LV:'Iespējots',},disabled:{EN:'Disabled',RU:'Запрещено',FR:'Désactivé',DE:'Inaktiv',ES:'Deshabilitadas',PT:'Desativado',JA:'オフにした',ZH:'已禁用',UK:'Вимкнено',PL:'Wyłączone',KK:'Өшірілген',IT:'Disabilitato',LV:'Atspējots',},};var lang=window.browserLang.toUpperCase();return lang&&data[key][lang]?data[key][lang]:data[key].EN}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}